### ISSUE TITLE
[BUG]: fix research_eval_demo bug

### ISSUE THREAD

**Issue by lwaekfjlk** [ulab-uiuc/research-town#663]
### Description of the bug

/Users/yuhaofei/anaconda3/envs/research-town/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Traceback (most recent call last):
  File "/Users/yuhaofei/Desktop/research-town/examples/research_eval_demo.py", line 89, in <module>
    main()
  File "/Users/yuhaofei/Desktop/research-town/examples/research_eval_demo.py", line 22, in main
    progress_db = ProgressDB(load_file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuhaofei/Desktop/research-town/research_town/dbs/db_progress.py", line 9, in __init__
    super().__init__(
  File "/Users/yuhaofei/Desktop/research-town/research_town/dbs/db_complex.py", line 17, in __init__
    self.load_from_json(load_file_path)
  File "/Users/yuhaofei/Desktop/research-town/research_town/dbs/db_complex.py", line 80, in load_from_json
    db.load_from_json(load_path, with_embed=with_embed, class_name=class_name)
  File "/Users/yuhaofei/Desktop/research-town/research_town/dbs/db_base.py", line 100, in load_from_json
    with open(os.path.join(save_path, file_name), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './research_town_demo_log/Insight.json'

### Steps To Reproduce

run that scripts

**Comment by lwaekfjlk** [comment]
confirmed with @timsanders256 that eval_demo can successfully run.
